# 本番環境用Docker Compose設定
# 使用方法: docker-compose -f docker-compose.prod.yml up -d

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production  # 本番用ステージを指定
    container_name: frontend_container_prod
    image: frontend_container_prod
    deploy:
      resources:
        limits:
          memory: 2G
    ports:
      - "3000:3000"  # 本番用ポートのみ
    networks:
      - app-network
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_container_prod
    image: backend_container_prod
    ports:
      - "8000:8000"  # APIのみ外部公開（メトリクスポートは非公開）
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
      - monitoring-network  # 将来の監視ツール用
    environment:
      - DATABASE_URL=postgresql://template_user:template_password@db:5432/template_db
      - ENVIRONMENT=production
      - CORS_ORIGINS=http://frontend:3000
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G

  db:
    image: postgres:13
    container_name: postgres_db_prod
    environment:
      POSTGRES_DB: template_db
      POSTGRES_USER: template_user
      POSTGRES_PASSWORD: template_password
      TZ: Asia/Tokyo
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    # 本番環境ではポートを外部公開しない（セキュリティ向上）
    # ports:
    #   - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U template_user -d template_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G

  # 将来実装予定の監視ツールスタック
  # prometheus:
  #   image: prom/prometheus
  #   container_name: prometheus
  #   networks:
  #     - monitoring-network
  #   volumes:
  #     - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

  # grafana:
  #   image: grafana/grafana
  #   container_name: grafana
  #   networks:
  #     - monitoring-network
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=admin

networks:
  app-network:
    driver: bridge
  monitoring-network:
    driver: bridge
    internal: true  # 外部アクセス禁止（監視ツール専用）

volumes:
  postgres_data_prod: