"""Initial migration

Revision ID: 97337ec4b949
Revises: 
Create Date: 2025-01-23 11:35:05.630645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97337ec4b949'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='ユーザーID (UUID)'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='ユーザー名'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='メールアドレス'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='パスワード（ハッシュ）'),
    sa.Column('contact_number', sa.String(length=15), nullable=True, comment='連絡先電話番号'),
    sa.Column('date_of_birth', sa.Date(), nullable=True, comment='生年月日'),
    sa.Column('user_role', sa.SmallInteger(), nullable=False, comment='ユーザー権限 (1: guest, 2: free, 3: regular, 4: admin, 5: owner)'),
    sa.Column('user_status', sa.SmallInteger(), nullable=False, comment='アカウント状態 (1: active, 2: suspended)'),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False, comment='更新日時'),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True, comment='削除日時'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
