name: Frontend Lint and Format Check

on:
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/github-actions_frontend_prettier_eslint.yml'
  push:
    branches: [main, develop]
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  lint_and_format:
    name: ESLint・Prettier・TypeScript Check
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Node.js をセットアップ
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: 依存関係をインストール
        run: npm ci

      - name: ESLint チェック
        run: npm run lint

      - name: Prettier フォーマットチェック
        run: npm run format:check

      - name: TypeScript 型チェック
        run: npm run typecheck

      - name: ビルドテスト
        run: npm run build