name: Backend Code Quality (Linting & Type Check)

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]
  workflow_dispatch:
    # 手動でこのワークフローをトリガーします。


jobs:
  lint_and_type_check:
    name: Lint and Type Check
    runs-on: ubuntu-latest
    # ジョブをUbuntu最新環境で実行します。

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # リポジトリのコードをチェックアウトします。
        # 後続のステップでコードベースにアクセスするための準備です。

      - name: Set up Backend Container
        run: |
          docker compose up -d backend
          sleep 15
        # docker-compose.ymlを使用して、backendコンテナを立ち上げる
        # 起動を待機

      - name: Check Backend Container Status
        run: |
          docker ps
          docker exec backend_container poetry --version
        # 起動中のDockerコンテナとPoetryの確認

      - name: Install Dependencies
        run: |
          docker exec backend_container poetry install
        # 依存関係のインストール（念のため）

      - name: Run Ruff Check
        run: |
          docker exec backend_container poetry run ruff check .
        # backendコンテナ内でruffを実行

      - name: Run Ruff Format Check
        run: |
          docker exec backend_container poetry run ruff format --check .
        # ruff formatでフォーマットチェック

      - name: Run MyPy Type Check
        run: |
          docker exec backend_container poetry run mypy .
        # backendコンテナ内でmypyを実行

      - name: Show Container Logs on Failure
        if: failure()
        run: |
          echo "=== Backend Container Logs ==="
          docker logs backend_container
        # 失敗時のコンテナログを表示
