name: Frontend Code Quality (Linting & Type Check)

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]
  workflow_dispatch:
    # 手動でこのワークフローをトリガーします。

jobs:
  lint_and_format:
    name: Lint and Type Check
    runs-on: ubuntu-latest
    # ジョブをUbuntu最新環境で実行します。

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # リポジトリのコードをチェックアウトします。
        # 後続のステップでコードベースにアクセスするための準備です。

      - name: Set up Frontend Container
        run: |
          docker compose build frontend
          docker compose run --rm frontend npm install
        # docker-compose.ymlを使用して、frontendコンテナをビルドし、依存関係をインストール

      - name: Check Frontend Container Status
        run: |
          docker compose run --rm frontend node --version
          docker compose run --rm frontend npm --version
        # Node.jsとnpmのバージョンを確認

      - name: Run ESLint Check
        run: |
          docker compose run --rm frontend npm run lint
        # frontendコンテナ内でESLintを実行

      - name: Run Prettier Format Check
        run: |
          docker compose run --rm frontend npm run format:check
        # Prettierでフォーマットチェック

      - name: Run TypeScript Type Check
        run: |
          docker compose run --rm frontend npm run typecheck:ci
        # frontendコンテナ内でTypeScript型チェックを実行

      - name: Run Build Test
        run: |
          docker compose run --rm frontend npm run build
        # ビルドテストを実行

      - name: Show Container Logs on Failure
        if: failure()
        run: |
          echo "=== Frontend Container Logs ==="
          docker logs frontend_container || echo "No frontend container found"
        # 失敗時のコンテナログを表示